version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ${OLLAMA_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - automation_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ${OPENWEBUI_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${OPENWEBUI_PORT}:8080"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    networks:
      - automation_net
    depends_on:
      - ollama

volumes:
  ollama_data:

networks:
  automation_net:
    external: true
